# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-10 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioriry', models.PositiveIntegerField(verbose_name='Prioridade')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Prioridade de Categoria',
                'verbose_name_plural': 'Prioridades de Categorias',
            },
        ),
    ]
