# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-10 00:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_categorypriority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorypriority',
            old_name='prioriry',
            new_name='priority',
        ),
    ]
